### ISSUE TITLE
Need to a local dev environment

### ISSUE THREAD

**Issue by arunpariyar** [techlabsms/techlabs_new#298]
Hi, 
I noticed that in order to be able to run the site locally one requires the access token from contentful. 
As a suggestion, may be the dev environment can make use of dummy data rather than from contentful in order it easy for developers to get onboard for working in small issues. 

Regards

**Comment by RichardMEN11** [comment]
Hey @arunpariyar thanks for mentioning. We will add the access token to passbolt. :-) In the meantime just shoot me a message at slack ;-)

**Comment by arunpariyar** [comment]
Thanks 👍
