### ISSUE TITLE
Next Batch Date is only shown when application is already open

### ISSUE THREAD

**Issue by Maxscha** [techlabsms/techlabs_new#397]
We used the location.nextBatchDate to announce our upcoming application periods, while leaving the application manually open with location.isOpen  which avoided a lot of questions from potential Techies when the next period starts.

With the new(4 months old) checks for actual application time this does not work. The workaround is to set the start application date before today, but that also activates the card under /apply.

Proposed idea: A new field to show a message when applications are closed. I can add the field in react, but I don't know how to add it in contentful.

Thanks

**Comment by RichardMEN11** [comment]
Thanks for your input! :-) Yes the setting of the dates is kind of weird because you have both - a date and the toggle. ( We should change it in the future) - Anyways I will work on your idea in the next days and keep you updated.

**Comment by Maxscha** [comment]
Hey @RichardMEN11,

Any updates on this?

**Comment by Maxscha** [comment]
![image](https://user-images.githubusercontent.com/12814709/138268466-90d68011-39f5-4c2b-9013-04c0d547fe09.png)
Maybe not the best solution, how it is, let me figure sth. out

**Comment by RichardMEN11** [comment]
Yes makes sense. It's different for each location. But I should have checked it 😅

**Comment by Maxscha** [comment]
Just opened another branch, which should fix it. 

Once this is merged as well I would make a quick update so the locations are aware what is displayed now.

**Comment by RichardMEN11** [comment]
Perfect! Thanks a lot! :-)
